/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package regis_klinik;

/**
 *
 * @author User
 */
public class GUI_RegisKlinik extends javax.swing.JFrame {

    /**
     * Creates new form GUI_RegisKlinik
     */
    public GUI_RegisKlinik() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kolomNama = new javax.swing.JTextField();
        kolomUltah1 = new javax.swing.JComboBox<>();
        kolomUltah2 = new javax.swing.JComboBox<>();
        kolomUltah3 = new javax.swing.JComboBox<>();
        kolomUmur = new javax.swing.JTextField();
        kolomID = new javax.swing.JTextField();
        kolomDokter = new javax.swing.JComboBox<>();
        rLakilaki = new javax.swing.JRadioButton();
        rPerempuan = new javax.swing.JRadioButton();
        kolomDaftar = new javax.swing.JButton();
        kolomReset = new javax.swing.JButton();
        kolomHarga = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        kolomReport = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kolomNama.setBackground(new java.awt.Color(204, 204, 255));
        getContentPane().add(kolomNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 180, 30));

        kolomUltah1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tgl", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        getContentPane().add(kolomUltah1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 50, 30));

        kolomUltah2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bln", "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec" }));
        getContentPane().add(kolomUltah2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 60, 30));

        kolomUltah3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Thn", "1980", "1982", "1983", "1985", "1986", "1988", "1989", "1991", "1992", "1994", "1995", "1997", "1998", "2000", "2001", "2003", "2004", "2006", "2007", "2009", "2010", "2012", "2013", "2015", "2016", "2018", "2019" }));
        getContentPane().add(kolomUltah3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 70, 30));

        kolomUmur.setBackground(new java.awt.Color(204, 204, 255));
        getContentPane().add(kolomUmur, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 180, 30));

        kolomID.setBackground(new java.awt.Color(204, 204, 255));
        getContentPane().add(kolomID, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, 180, 30));

        kolomDokter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "Dokter Rafi (BPJS)", "Dokter Intan (Umum)", "Dokter Roland (Spesialis)", "Dokter Ana (Gigi)" }));
        getContentPane().add(kolomDokter, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 440, 180, 30));

        rLakilaki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rLakilakiActionPerformed(evt);
            }
        });
        getContentPane().add(rLakilaki, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 500, -1, -1));

        rPerempuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rPerempuanActionPerformed(evt);
            }
        });
        getContentPane().add(rPerempuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 540, -1, -1));

        kolomDaftar.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        kolomDaftar.setForeground(new java.awt.Color(0, 0, 153));
        kolomDaftar.setText("DAFTAR");
        kolomDaftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kolomDaftarActionPerformed(evt);
            }
        });
        getContentPane().add(kolomDaftar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 510, 130, 50));

        kolomReset.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        kolomReset.setForeground(new java.awt.Color(0, 0, 153));
        kolomReset.setText("RESET");
        kolomReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kolomResetActionPerformed(evt);
            }
        });
        getContentPane().add(kolomReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 510, 140, 50));

        kolomHarga.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        kolomHarga.setBorder(new javax.swing.border.MatteBorder(null));
        kolomHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kolomHargaActionPerformed(evt);
            }
        });
        getContentPane().add(kolomHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, 170, 50));

        jLabel2.setBackground(new java.awt.Color(204, 204, 255));
        jLabel2.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 0));
        jLabel2.setText("ADMINISTRASI");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, 150, 50));

        kolomReport.setColumns(20);
        kolomReport.setRows(5);
        kolomReport.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane1.setViewportView(kolomReport);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 310, 220, 150));

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 0));
        jLabel3.setText("REPORT");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 280, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/regis_klinik/TA.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rLakilakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rLakilakiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rLakilakiActionPerformed

    private void rPerempuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rPerempuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rPerempuanActionPerformed

    private void kolomResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kolomResetActionPerformed
        // TODO add your handling code here:
        kolomNama.setText("");
        kolomUltah1.setSelectedItem("Tgl");
        kolomUltah2.setSelectedItem("Bln");
        kolomUltah3.setSelectedItem("Thn");
        kolomUmur.setText("");
        kolomID.setText("");
        kolomDokter.setSelectedItem("Pilih");
        rPerempuan.setText("");
        rLakilaki.setText("");
        kolomReport.setText("");
        kolomHarga.setText("");
        
    }//GEN-LAST:event_kolomResetActionPerformed

    private void kolomDaftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kolomDaftarActionPerformed
        // TODO add your handling code here:
        String nama = kolomNama.getText();
        int tanggal = kolomUltah1.getSelectedIndex();
        int bulan = kolomUltah2.getSelectedIndex();
        int tahun = kolomUltah3.getSelectedIndex();
        String usia = kolomUmur.getText();
        String ID = kolomID.getText();
        int dokter = kolomDokter.getSelectedIndex();
        String data = kolomHarga.getText();
        String JK;
        if (rPerempuan.isSelected()){
	JK = "Perempuan";
        }else {
	JK = "Laki-Laki";
        }
       
        int harga = 0;   
        int total = 0;
switch(dokter){
            case (0):
                harga = 0;
                break;
            case (1):
                harga = 0;
                break;
            case (2):
                harga = 75000;
                break;
            case (3):
                harga = 200000;
                break;
            case (4):
                harga = 335000;
            }
            total = harga;

kolomHarga.setText("        Rp. "+total);
kolomReport.setText("Nama Pasien : "+nama+" \nTanggal Lahir: "+kolomUltah1.getItemAt(tanggal)+" "+kolomUltah2.getItemAt(bulan)+" "+kolomUltah3.getItemAt(tahun)+" \nUsia : "+usia+" \nJenis Kelamin : "+JK+"  \nNo ID : "+ID+" \nTrimakasih "+nama+" Sudah Mendaftar \nMohon Tunggu Panggilan dari "+kolomDokter.getItemAt(dokter));
    }//GEN-LAST:event_kolomDaftarActionPerformed

    private void kolomHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kolomHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kolomHargaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_RegisKlinik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_RegisKlinik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_RegisKlinik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_RegisKlinik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_RegisKlinik().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton kolomDaftar;
    private javax.swing.JComboBox<String> kolomDokter;
    private javax.swing.JTextField kolomHarga;
    private javax.swing.JTextField kolomID;
    private javax.swing.JTextField kolomNama;
    private javax.swing.JTextArea kolomReport;
    private javax.swing.JButton kolomReset;
    private javax.swing.JComboBox<String> kolomUltah1;
    private javax.swing.JComboBox<String> kolomUltah2;
    private javax.swing.JComboBox<String> kolomUltah3;
    private javax.swing.JTextField kolomUmur;
    private javax.swing.JRadioButton rLakilaki;
    private javax.swing.JRadioButton rPerempuan;
    // End of variables declaration//GEN-END:variables
}
